---
title: "Trabalho Séries Temporais"
author: "Samara Almeida Silva"
date: "2023-05-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(yfR)
library(ggplot2)

```


```{r}
nome_acao <- "SEQL3.SA"   # Código no Yahoo Finance
data_ini  <- "2023-01-01" # Data de inicio
data_fim  <- "2023-05-17" # Data de fim
precos <- yf_get(tickers = nome_acao, first_date = data_ini, last_date = data_fim)
head(precos)
```


```{r}

ggplot(precos) + 
  geom_line(aes(x =ref_date, y = price_adjusted), color = "green4") +
  xlab("Tempo") + ylab("Preço")+
  theme_bw()
```
```{r}
ggplot(precos) + 
  geom_line(aes(x =ref_date, y = ret_adjusted_prices), color = "green4") +
  xlab("Tempo") + ylab("Retorno")+
  theme_bw()
```
```{r}
retornos = precos$ret_adjusted_prices[-1]
op = par(mfrow = c(1,2))
acf(retornos)
acf(retornos^2)
par(op)
```
```{r}
acf(retornos)

```

```{r}
Box.test(retornos, type = "Ljung-Box", lag = 10)
```


```{r}
summary(retornos)

```

```{r}
retornos_c = scale(retornos, center = TRUE, scale = FALSE)
acf(retornos_c^2)
```
```{r}
#install.packages("rugarch")
library(rugarch)
```

```{r}
spec <- ugarchspec(mean.model = list(armaOrder = c(0, 0), include.mean = FALSE),
                   variance.model = list(model = 'sGARCH', garchOrder = c(3, 0)),
                   distribution = 'norm')

fit_01 <- ugarchfit(spec, retornos_c, solver = 'hybrid')
fit_01
```

```{r}
spec <- ugarchspec(mean.model = list(armaOrder = c(0, 0), include.mean = FALSE),
                   variance.model = list(model = 'sGARCH', garchOrder = c(4, 0)),
                   distribution = 'norm')
fit_02 <- ugarchfit(spec, retornos_c, solver = 'hybrid')
fit_02
```

```{r}
spec <- ugarchspec(mean.model = list(armaOrder = c(0, 0), include.mean = FALSE),
                   variance.model = list(model = 'sGARCH', garchOrder = c(5, 0)),
                   distribution = 'norm')
fit_03 <- ugarchfit(spec, retornos_c, solver = 'hybrid')
fit_03
```


```{r}
spec <- ugarchspec(mean.model = list(armaOrder = c(0, 0), include.mean = FALSE),
                   variance.model = list(model = 'sGARCH', garchOrder = c(6, 0)),
                   distribution = 'norm')
fit_04 <- ugarchfit(spec, retornos_c, solver = 'hybrid')
fit_04
```


```{r}
spec <- ugarchspec(mean.model = list(armaOrder = c(0, 0), include.mean = FALSE),
                   variance.model = list(model = 'sGARCH', garchOrder = c(7, 0)),
                   distribution = 'norm')
fit_05 <- ugarchfit(spec, retornos_c, solver = 'hybrid')
fit_05
```




```{r}

#esse deu mais sigificativo e melhorou ACF


spec <- ugarchspec(mean.model = list(armaOrder = c(5, 0), include.mean = FALSE),
                   variance.model = list(model = 'sGARCH', garchOrder = c(1, 0)),
                   distribution = 'norm')
fit_06 <- ugarchfit(spec, retornos_c, solver = 'hybrid')
fit_06
```


```{r}

spec <- ugarchspec(mean.model = list(armaOrder = c(0, 0), include.mean = FALSE),
                   variance.model = list(model = 'sGARCH', garchOrder = c(2, 0)),
                   distribution = 'norm')
fit_07 <- ugarchfit(spec, retornos_c, solver = 'hybrid')
fit_07
```



```{r}
e_hat = fit_06@fit$residuals/fit_06@fit$sigma
op = par(mfrow = c(1,2))
acf(e_hat)
acf(e_hat^2)
par(op)

```




```{r}
qqnorm(e_hat)
qqline(e_hat)
```


```{r}
###essa parte não entendi 


fore_08 = ugarchforecast(fit_07, n.ahead = 5)
fore_08
```